// Generated by the WOLips Templateengine Plug-in at 24 janv. 2008 14:07:52

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSMutableArray;

/**
 * Ecran de maintenance systeme de l'application
 * 
 * @author ctarade
 */
public class SwapSysteme extends A_AdministrationSwapView {

	/** la duree en secondes pour l'arret de l'application */
	public Integer ttlStop;

	private final static int DEFAUT_TTL_STOP = 600;

	/** item session */
	public Session sessionItem;

	public SwapSysteme(WOContext context) {
		super(context);
	}

	/*
	 * @see AbsAdministrationSwapView#initComponent()
	 */
	protected void initComponent() {
		ttlStop = new Integer(DEFAUT_TTL_STOP);
	}

	/**
	 * Lancer le compte a rebourd de l'arret de l'application
	 * 
	 * @return
	 */
	public WOComponent startProcedureStop() {
		if (ttlStop != null && ttlStop.intValue() > 0) {
			dtApp().scheduleAppStop(ttlStop.intValue());
		}
		return null;
	}

	/**
	 * Liste des sessions ouvertes
	 * 
	 * @return
	 */
	public NSMutableArray<Session> getSessionArray() {
		return DTSessionManager.getSessionArray();
	}

	/**
	 * 
	 * @return
	 */
	public String getSessionItemIpAddress() {
		String ip = "";

		ip = DTSessionManager.getIpForSession(sessionItem);

		return ip;
	}

	// boolean interface

	/**
	 * On autorise l'arret que par un super admin et si la procedure n'est pas
	 * deja en cours
	 */
	public boolean isDisabledFieldsStartProcedureStop() {
		return !dtUserInfo().hasDroit(DTUserInfo.DROIT_ADMIN_SUPER) || dtApp().appWillStop();
	}
}