CREATE TABLE DT3.DISCUSSION
(
  DIS_ORDRE        NUMBER                       NOT NULL,
  INT_ORDRE        NUMBER                       NOT NULL,
  TRA_ORDRE        NUMBER,
  DIS_ORDRE_PERE   NUMBER,
  DIS_NO_INDIVIDU  NUMBER                       NOT NULL,
  DIS_MESSAGE  	   VARCHAR2(4000)               NOT NULL,
  DIS_DATE  	   DATE			                NOT NULL,
  D_CREATION       DATE                         DEFAULT SYSDATE               NOT NULL,
  D_MODIFICATION   DATE                         DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE SEQUENCE DT3.SEQ_DISCUSSION NOCACHE;

COMMENT ON TABLE DT3.DISCUSSION IS 'Dialogue entre intervenants et demandeurs';
COMMENT ON COLUMN DT3.DISCUSSION.DIS_ORDRE IS 'Clé primaire';
COMMENT ON COLUMN DT3.DISCUSSION.INT_ORDRE IS 'Demande concernée (table DT3.INTERVENTION)';
COMMENT ON COLUMN DT3.DISCUSSION.TRA_ORDRE IS 'Traitement concerné (table DT3.TRAITEMENT)';
COMMENT ON COLUMN DT3.DISCUSSION.DIS_ORDRE_PERE IS 'Message de discussion auquel s''adresser (table DT3.DISCUSSION)';
COMMENT ON COLUMN DT3.DISCUSSION.DIS_NO_INDIVIDU IS 'Auteur du message (table GRHUM.INDIVIDU_ULR)';
COMMENT ON COLUMN DT3.DISCUSSION.DIS_MESSAGE IS 'Contenu du message';
COMMENT ON COLUMN DT3.DISCUSSION.DIS_DATE IS 'Date du message';
COMMENT ON COLUMN DT3.DISCUSSION.D_CREATION IS 'Date de création de l''enregistrement (interne)';
COMMENT ON COLUMN DT3.DISCUSSION.D_MODIFICATION IS 'Date de dernière modification de l''enregistrement (interne)';

ALTER TABLE DT3.DISCUSSION ADD (
  CONSTRAINT DISCUSSION_PK
 PRIMARY KEY
 (DIS_ORDRE));

ALTER TABLE DT3.DISCUSSION ADD (
  CONSTRAINT FK_DISCUSSION_INTERVENTION 
 FOREIGN KEY (INT_ORDRE) 
 REFERENCES DT3.INTERVENTION (INT_ORDRE),
  CONSTRAINT FK_DISCUSSION_TRAITEMENT 
 FOREIGN KEY (TRA_ORDRE) 
 REFERENCES DT3.TRAITEMENT (TRA_ORDRE),
  CONSTRAINT FK_DISCUSSION_DISCUSSION 
 FOREIGN KEY (DIS_ORDRE_PERE) 
 REFERENCES DT3.DISCUSSION (DIS_ORDRE));
