CREATE TABLE DT3.TRAITEMENT_TYPE
(
  TTY_KEY      NUMBER                           NOT NULL,
  TTY_LIBELLE  VARCHAR2(64)                     NOT NULL,
  TTY_CODE     VARCHAR2(1)                      NOT NULL
)

LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

COMMENT ON TABLE DT3.TRAITEMENT_TYPE IS 'Table de typage des traitements.';
COMMENT ON COLUMN DT3.TRAITEMENT_TYPE.TTY_KEY IS 'Clé primaire';
COMMENT ON COLUMN DT3.TRAITEMENT_TYPE.TTY_LIBELLE IS 'Libellé du type de traitement';
COMMENT ON COLUMN DT3.TRAITEMENT_TYPE.TTY_CODE IS 'Code du type de traitement (ne pas modifier)';


ALTER TABLE DT3.TRAITEMENT_TYPE ADD (
  CONSTRAINT TRAITEMENT_TYPE_PK
 PRIMARY KEY
 (TTY_KEY));
 
INSERT INTO DT3.TRAITEMENT_TYPE ( TTY_KEY, TTY_LIBELLE, TTY_CODE ) VALUES ( 1, 'Traitement textuel', 'T'); 
INSERT INTO DT3.TRAITEMENT_TYPE ( TTY_KEY, TTY_LIBELLE, TTY_CODE ) VALUES ( 2, 'Prestation', 'P'); 
INSERT INTO DT3.TRAITEMENT_TYPE ( TTY_KEY, TTY_LIBELLE, TTY_CODE ) VALUES ( 3, 'Commande', 'C'); 
INSERT INTO DT3.TRAITEMENT_TYPE ( TTY_KEY, TTY_LIBELLE, TTY_CODE ) VALUES ( 4, 'Livraison', 'L'); 
INSERT INTO DT3.TRAITEMENT_TYPE ( TTY_KEY, TTY_LIBELLE, TTY_CODE ) VALUES ( 5, 'Numéro de série', 'S'); 
 

ALTER TABLE DT3.TRAITEMENT ADD (TTY_KEY  NUMBER                               DEFAULT 1                     NOT NULL);
ALTER TABLE DT3.TRAITEMENT ADD (TRA_TRAITEMENT_ADDITIONNEL VARCHAR2(2000));


COMMENT ON TABLE DT3.TRAITEMENT IS 'Traitement relative à une demande de travaux';
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_ORDRE IS 'Clé primaire';
COMMENT ON COLUMN DT3.TRAITEMENT.NO_INDIVIDU IS 'Individu ayant effectué le traitement (table GRHUM.INDIVIDU_ULR)';
COMMENT ON COLUMN DT3.TRAITEMENT.INT_ORDRE IS 'Demande de travaux concernée (table DT3.INTERVENTION)';
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_ETAT IS 'Etat actuel de la demande de travaux (table DT3.ETAT_DT)';
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_COMMENTAIRE_INTERNE IS 'Le commentaire interne relatif au traitement (à conserver pour historique)';
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_DATE_DEB IS 'Date de début du traitement';
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_DATE_FIN IS 'Date de fin du traitement';
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_CONSULTABLE IS 'Indique si le traitement est public (O/N)';
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_TRAITEMENT IS 'Le détail du traitement';
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_TRAITEMENT_ADDITIONNEL IS 'Complément au traitement';

COMMENT ON COLUMN DT3.TRAITEMENT.TTY_KEY IS 'Le type de traitement (table DT3.TRAITEMENT_TYPE)';
ALTER TABLE DT3.TRAITEMENT
 ADD CONSTRAINT FK_TRAITEMENT_TYPE 
 FOREIGN KEY (TTY_KEY) 
 REFERENCES DT3.TRAITEMENT_TYPE (TTY_KEY);
 
update DT3.TRAITEMENT set tty_key = 2 where int_ordre in (select int_ordre from DT3.INTERVENTION_REPRO); 