--
-- Transformation du type de donnees de l'attribut INT_MOTIF
-- de VARCHAR2 vers CLOB 
--
ALTER TABLE DT3.INTERVENTION ADD (INT_MOTIF_CLOB  CLOB);
COMMENT ON COLUMN DT3.INTERVENTION.INT_MOTIF_CLOB IS 'Motif complet de la demande de travaux';
UPDATE DT3.INTERVENTION SET INT_MOTIF_CLOB = INT_MOTIF;
ALTER TABLE DT3.INTERVENTION DROP COLUMN INT_MOTIF;
ALTER TABLE DT3.INTERVENTION RENAME COLUMN INT_MOTIF_CLOB TO INT_MOTIF;

--
-- Transformation du type de donnees de l'attribut TRA_TRAITEMENT
-- de VARCHAR2 vers CLOB 
--
ALTER TABLE DT3.TRAITEMENT ADD (TRA_TRAITEMENT_CLOB  CLOB);
COMMENT ON COLUMN DT3.TRAITEMENT.TRA_TRAITEMENT_CLOB IS 'Contenu du traitement';
UPDATE DT3.TRAITEMENT SET TRA_TRAITEMENT_CLOB = TRA_TRAITEMENT;
ALTER TABLE DT3.TRAITEMENT DROP COLUMN TRA_TRAITEMENT;
ALTER TABLE DT3.TRAITEMENT RENAME COLUMN TRA_TRAITEMENT_CLOB TO TRA_TRAITEMENT;