CREATE TABLE DT3.INTERVENTION_CODE_ANA
(
  INT_ORDRE  NUMBER                             NOT NULL,
  CAN_ID     NUMBER                             NOT NULL,
  QUOTITE    NUMBER                             NOT NULL
);

COMMENT ON TABLE DT3.INTERVENTION_CODE_ANA IS 'Description de l''affectation des codes analytiques aux demandes de travaux';

COMMENT ON COLUMN DT3.INTERVENTION_CODE_ANA.INT_ORDRE IS 'la dt (table DT3.INTERVENTION)';

COMMENT ON COLUMN DT3.INTERVENTION_CODE_ANA.CAN_ID IS 'le code analytique';

COMMENT ON COLUMN DT3.INTERVENTION_CODE_ANA.QUOTITE IS 'la quotité';

ALTER TABLE DT3.INTERVENTION_CODE_ANA ADD (
  CONSTRAINT INTERVENTION_CODE_ANA_PK
 PRIMARY KEY
 (INT_ORDRE, CAN_ID));

ALTER TABLE DT3.INTERVENTION_CODE_ANA ADD (
  CONSTRAINT FK_INT_CODE_ANA_INT 
 FOREIGN KEY (INT_ORDRE) 
 REFERENCES DT3.INTERVENTION (INT_ORDRE));
